### ISSUE TITLE
perform "topology check" before creating any links and/or containers

### ISSUE THREAD

**Issue by hellt** [srl-wim/container-lab#113]
in addition to the existing checks, the following checks need to be added before we attempt to create a lab

- [x] every endpoint appears in the list of links only once (added in #266)
- [x] ensure that container images are either available locally or pullable (added in #267)
- [x] referred linux bridges exist in the lab host (addressed in #118 )
- [x] config files referenced in topo with `config` are present by the provided paths (added in #268)
- [x] license files referenced in topo with `license` element must have a file by that path (added in #268)
