### ISSUE TITLE
add support for running vrnetlab based containers

### ISSUE THREAD

**Issue by hellt** [srl-wim/container-lab#125]
It is possible to build KVM containers with VMs inside. [Vrnetlab](https://github.com/plajjan/vrnetlab) project does a good job in helping that.

- [x] vr-sros added in #235 
- [x] vr-vmx added in #237 
- [x] vr-xrv added in #238
